version: "3.9"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    ports:
      - 8000:8000
      #- 9000:9000
    networks: 
      - vpn-net:
          ipv4_address: 172.110.1.4
      - nginx-network
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  nginx-network:
    external: true